name: Build & Test
on:
  push:
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules(yarn.lock)
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('ttis-back/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-${{ env.cache-name }}
      - name: package-install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: publish
        if: contains(github.ref, 'refs/tags')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          a=($(echo $GITHUB_REF | sed -n -r 's/^refs\/tags\/([^-]*)-(.*)$/\1 \2/p')) tag=${a[0]} version=${a[1]}
          echo publish $version [$tag]
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --tag $tag
